skin: {
  url: "http://textures.minecraft.net/texture/df95fc23392af7e5c5c20c76a2208df4922b108f2c89e33522402612c58db508"
}
display_name: {
  text: "Tokoyami Towa"
  color: "#805A9E"
}
        return new Idol(new SaintQuartzItem(plugin), new HolyFireBlock(plugin)) {
