skin: {
  url: "http://textures.minecraft.net/texture/1601c812f0397c82139ab6baea614e69fd8aa3e563b57437a9fe0879576f6b51"
}
display_name: {
  text: "Shishiro Botan"
  color: "#9E8788"
}
items: ["backdash"]
