skin: {
  url: "http://textures.minecraft.net/texture/c4b7596eb99e38b917d9b6b6c8e20100408ce8a66f00dd5cca487eb2a909088c"
}
display_name: {
  text: "Mori Calliope"
  color: "#9F0306"
}
items: ["memento"]