skin: {
  url: "http://textures.minecraft.net/texture/35c975deb28de3364787908fb0f693b200eb16c50ffd7fcf62cdbe23665b8f39"
}
display_name: {
  text: "Shirakami Fubuki"
  color: "#6BBFD9"
}
        return new Idol(new PlowBook(plugin)) {
